version: "3.9"

services:
  db:
    restart: always
    image: postgres:14
    ports:
      - '65432:5432'
    env_file:
      - .env
    volumes:
      - db_data_2:/var/lib/postgresql/data
    networks:
      - bot_management_network
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db

networks:
  bot_management_network:

volumes:
  db_data_2:
  db_data:
