# Generated by Django 4.1.7 on 2023-03-02 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 2, 12, 29, 17, 855441)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
