# Generated by Django 4.1.7 on 2023-03-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0004_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stylistprofile',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usualuserprofile',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
