# Generated by Django 4.1.7 on 2023-04-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0005_alter_service_deleted_at_alter_store_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylistprofile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='usualuserprofile',
            name='title',
        ),
    ]
