# Generated by Django 4.1.7 on 2023-04-06 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_management', '0006_remove_stylistprofile_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylistprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usualuserprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='stylistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usualuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
