# Generated by Django 4.1.7 on 2023-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0008_userprofile_remove_usualuserprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ST', 'Stylist'), ('US', 'Usual')], default='US', max_length=2),
        ),
    ]
