# Generated by Django 4.2.3 on 2023-08-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0012_remove_service_store_store_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_management.store'),
        ),
    ]
